name: Upload Release

on:
  push:
    # branches:
    #   - master

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build 
        id: build
        run: |
          sudo npm install -g vsce
          cd ..
          wget https://github.com/TerosTechnology/colibri/archive/master.zip
          unzip master.zip
          cp colibri-master colibri -r
          cd vscode-terosHDL
          npm install
          cd node_modules/jsteros/python_modules
          mkdir Python33 -p
          mkdir Python34 -p
          mkdir Python35 -p
          mkdir Python36 -p
          mkdir Python37 -p
          mkdir Python38 -p
          cd ../../../
          vsce package
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          draft: true
          automatic_release_tag: latest
          files: |
            *.vsix